---
title: "Research Experience and Publications"
output: 
  html_document:
    toc: true
    toc_float: true
---

<style type="text/css">

h1.title {
  text-align: center;
}

</style>

&nbsp;

## Columbia Mailman School of Public Health

### Current Research for Publication

*Masters Thesis*
<ul>
<li>An exploratory analysis examining the effects the COVID-19 pandemic has had on the wellbeing of frontline healthcare providers in New York City</li>
</ul>

&nbsp;

### Unpublished Research

*Human Resources for Health in Democratic Republic of the Congo*
<ul>
<li>Acknowledged in manuscript for contributions in literature search, editing, and preparing manuscript for publication</li>
</ul>

&nbsp;

### Published Research

*Human Resources for Health in Democratic Republic of the Congo*
<ul>
<li>Contributed as author in research focused on increasing rural rotations of nursing students in Democratic Republic of the Congo to better the response and treatment to HIV/AIDS</li>
<li>In progress of being published currently in Human Resources for Health journal</li>
</ul>

&nbsp;

## James Madison University

### Past Projects

*Relationship between body image, eating disorders, and social media in college students*
<ul>
<li>Assisted Dr. Aimee Johnson in searching literature based on this topic</li>
</ul>

&nbsp;

*Relationship between narcissism and perceived acceptance rates to graduate programs*
<ul>
<li>Examined perceived acceptance rates to graduate programs among JMU students pursuing a graduate education in a health-related field</li>
</ul>
